### ISSUE TITLE
Switch to GeckoFX

### ISSUE THREAD

**Issue by deavmi** [Walkman100/BasicBrowser#1]
Switch to something open-source, hence always better, switch to Gecko, switch to GeckoFX. I can do the switch easily tomorrow. I have done it a million times.
- [x] upload DLLs to [`Resources` folder](https://github.com/Walkman100/BasicBrowser/tree/master/Resources)
- [x] change line on new tab that declares the browser from

``` vb
Dim WebBrowser As New WebBrowser
```

to

``` vb
Dim WebBrowser As New <whatever geckoFX uses>
```
- [x] fix anything that might have been broken (different commands e.t.c.)
- [x] test that it works
- [ ] upload release

**Comment by Walkman100** [comment]
ok do it then, i have no idea how.

**Comment by Walkman100** [comment]
Make sure it doesn't mess up any of my existing code (BasicBrowser is already quite complex)

**Comment by deavmi** [comment]
It shouldn't it uses the same syntax.

**Comment by Walkman100** [comment]
Ok I'll do it then.

**Comment by Walkman100** [comment]
Added in ab73692d494da3b777cd737d715643fd4855a3ca (forgot to mention issue in commit message)

**Comment by Walkman100** [comment]
Ok it compiles and runs now, but as soon as it starts it says:

```
---------------------------
XULRunner Not Found
---------------------------
Couldn't find XULRunner in 'C:\Users\Matthew\Documents\GitHub\BasicBrowser\bin\Debug'.  Call Xpcom.Initialize() in your application startup code and specify the directory where XULRunner is installed.

If you do not have XULRunner installed, click Yes to open the download page.  Otherwise, click No, and update your application startup code.
---------------------------
Yes   No   
---------------------------
```

So now we have to get XULRunner.

**Comment by deavmi** [comment]
Oh ya @Walkman100

**Comment by deavmi** [comment]
Get the one that corresponds to your GeckoFX version

**Comment by Walkman100** [comment]
@deavmi can you do it.

**Comment by deavmi** [comment]
@Walkman100 Get XUL?

**Comment by Walkman100** [comment]
nvm, I will do it. But not anytime soon, since I'm going to bed now because I have to leave at 6:30 tomorrow for an archery competition, then we have a braai in the afternoon. So I'll probably get it done on Sunday.

**Comment by deavmi** [comment]
@Walkman100 K.

**Comment by Walkman100** [comment]
Yeah. Sunday looks good

**Comment by deavmi** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Lekker

On 10/18/2014 7:02 PM, ░▒▓█│【Walkman】│█▓▒░ wrote:

> Yeah.Sunday looks good
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/Walkman100/BasicBrowser/issues/1#issuecomment-59621689
> 
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v2

iQIcBAEBAgAGBQJUQrmbAAoJEGJdg7ItGNiYT9MP/A7RYv+/3BFCEc5oX584/vKz
kss11YhHPAagxTF99t+7toaHnSCrvNyigHDV3PxEfX8BBefDRZma6easiq/7GatD
eVlRhoKPR2Nz/KUMXtop2da0qzwtZC0IG683pp5jVgefmK6hqaI0iRwWP/llBf//
W0Hf/4Kpm48nCw6L1kpz40X0pqOLGewGzHlmcE/aXqrg8kFEhvxt6XJcYJkVgUFx
3f3F9wR75YE2CHN+XEXtQ/bMv0dVvPQQYM6ArTHv4tuBWEx8injR4b53hqbjslyA
EhFkuowjgRb6IjQ/+rsBRmYF9JoDGZLpGfcLPRZHMiaxzHWmiw63oiyCIL8spvQA
boTbVtomuRjaFJ/1bm4I4yfpm4ZHo5Cb6WeGENWWHGhL8ihZV4FkeAVLSY20s6Bb
cnDEHPnnAuDKyyXpVAY7caxfwzY3Wo/G1AJWkrbA9WqYKqvZ1koZjXWECHZCepff
lUdu5yGBMCWdB9FPLWZ73LloDIgsPJFKcYeby3v3F3EOLAzGg7yB6s4AHk0wS9rM
Zrw/73mFpwbV6/IPEaAw2qLlh1iACyE8/vjH4llUArg2L1PANhmC0VlX7UrswT36
hxm0+RGB/pEB7B8S5t2UhYpBbhUJW7M7PCy7LLi8L829c3RsxTHUcwJCcjoGozFn
v2dsyMs7UCeXE1qssTEL
=Izsd
-----END PGP SIGNATURE-----

**Comment by deavmi** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

WHich version of GeckoFX are youn using? GeckoFX 22?

On 10/18/2014 7:02 PM, ░▒▓█│【Walkman】│█▓▒░ wrote:

> Yeah.Sunday looks good
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/Walkman100/BasicBrowser/issues/1#issuecomment-59621689
> 
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v2

iQIcBAEBAgAGBQJUQrmvAAoJEGJdg7ItGNiYZ48P/1/KuyiLN6hym50YKUYSJ+0j
Nh4wXcRJxWttgNoxAUOA8WYJBzgqcwiEJG6C/7QBr8BXyTQ8GTWxFvIL9sxSFubn
XlTf2+OpNz8FnqJwllgVpPYPWlOj+KPQwI9mlsTLbRRNBpjVv/CJWx4pQSrvcalN
dMefuzK9MrutS/DmEISzqrFIfkZPQe16yX1J+H7n4nyJacDorKKd+ekaj2DIPMiY
5u54N15B1AX5vNWQfTfGUH2nf1ajDEwVZKM4oQiIc43vfubzb/OJAJtKjx5nWfbt
TttRWydUhG+cXELuQv9D2TD7V9HesepfeetA38ro8lPDhNgAcEXazkdQYCyQwrMs
Q3Arv5mL+L0hklJWN9CD00+LI80lSHeebYUejsR9YzBIWHWs6ImxUiv53hU1iaey
KH3jRnZpQ01+adw510cdyZu7J1hqgrzkljr1dIr+v8L862qf8FWcGgoKZlCEPKTH
nWP2KremqK3eLfyy3d5btTeNu4N/FXY5npcMHcC/Ijj943/xPRGuw3eNYBJBrKcf
ChdXkhKr5yi+LyeAQmgfYkojuHKdhBWgiD6XHV1GI28NBWj0iXBYN/3ANk1Tsxg6
LHdP2or0lIHVUrodmJl41dLy/JVwdMSLvz85ncYo7O2+wkHxHKkxOCECLlwlqZQ3
BW9Wgxy6EWNfHIUFT+wm
=ei3j
-----END PGP SIGNATURE-----

**Comment by Walkman100** [comment]
STOP SPAMMING

**Comment by Walkman100** [comment]
IDGAF ABOUT YOUR PGP SIGNATURES

**Comment by Walkman100** [comment]
GeckoFX has been moved to https://github.com/Walkman-Mirror/BasicBrowserGecko.
