### ISSUE TITLE
GPL v3

### ISSUE THREAD

**Issue by deavmi** [Walkman100/BasicBrowser#5]
Why Public Domain, it's a great browser, it's shit fast.

**Comment by Walkman100** [comment]
Nope.

**Comment by deavmi** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

U wot m8

On 10/9/2014 9:16 PM, ░▒▓█│【Walkman】│█▓▒░ wrote:

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBAgAGBQJUNuBgAAoJEGJdg7ItGNiYfAsP/3Qds6GFnhuFn9UuBgy38JpH
yETzJCi51GXjWdIG0pu8vz0+wwAw3shRvb7nlvTpijbLI1TU09IA2Z/g5MckMEcV
oB1mr4EvcHTd9VStR3K14Tm1cMtWUdfsvo2Ro+Gn40qHRT5TpB6esPnYtFMUona3
185pLujwuWiAA37IwNvL4U8RdE0+Gixfd0TuqnU+qw11qet4VnIlxBLt0cs9TdGH
AQtu0YEYkiX+YbTKdWUJ8tphCNSkVErY+PEmiSJ26Bmn5QAbTr00/dHhl+LFJNn/
g5EhfTgr/sZXVwDJ86IYf1gcxJJzvOwRHf6V/rkpBNmGqh0CV/RXYXTJtOJMucZQ
w00jLYPBZCc7UkYLovUkArcwOlZAB6FDRRByrevhKMr50WkVAMQxgtHKjqWwxLgw
SQOlp932f5yO2H8NbwSnPU3QAHX0TklA2gawR1ztv9oBP/L9Ea3obVOYCmJ+DaVo
3YjPcbLp7jBSPED+90sIwFSE7x7/M6cmVXPgrSe4M5sglPvWAJ9ILDwbat/xDW6O
hzsVau7FYZLo1qNV94YNKxLZPa9gWjoNGETFbrx/pz2f0UotmuSHjjV10OedS+bL
fQWxuP2fF5PufGd1Z0ZNKcZ4AC99gM4ADCl7R8Vuk59GcKXSbvl+M7SMLFrqY52x
13VRiXs+AYeZtsJeLQc/
=T9rf
-----END PGP SIGNATURE-----

**Comment by deavmi** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

U wot m8

On 10/9/2014 9:16 PM, ░▒▓█│【Walkman】│█▓▒░ wrote:

> Closed #5.
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/Walkman100/BasicBrowser/issues/5#event-176539820
> 
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v2

iQIcBAEBAgAGBQJUNuBmAAoJEGJdg7ItGNiYwVkP+gKr9F0GBwLFH9uo1fyiTUiJ
+e9Ui4sIptYwDHqCjP6YmwxWVElc9rAj1aZXCyboOdCKBUL9dNiZw5kaHjplGM0w
ZgXjZxiHkR+uWIvz3GaInMgSTLC6mgdwME0Vsr7bo+j1eRK/KS2sTjc7WTlrtcBq
aVRpGsKkQAcWaJ9GV8PvKtSpsgK5HhX19Z2xKg1oR/MQWcAFhpfoCcIksYSn3eD/
Nx74uqP4wn0RQcu4ex5RcOphecKJa6eyIjR87BAuALmnDQKZkRaX0487TMKT4YrT
HHUhbmlS6Q0JuR7HDBMqprvYfOikphMjxriacJyF1+u4k/GslFGlW/grpVbOTEZK
Xwl7LPgTBVcSZ+zxbaVnrQDzVUnl3RE0U9JhoP582AJBUU+J8pFU9rKarO4jpeeQ
qUlMPES9ZmCJyXQRaD23r1kS7RmyQJrpKxXtZCU6Ez8iYEp9AFxtcx+YGJ5A6bQW
IzhKngbSanCMpkIVVfx1MRtnAu2W/vgYDXwQ0B5RrHcSBOsahjimAiIh9fPGoibW
M3Ib6edmqQRXVQLM3Ii3ujElL1Z0eC9mJW9JFRpqLaKps1eO1+HqyNF4LutrRD/8
LleZPMQLi837h9ndSzm2uAKZ7AhOw226QTXOtq+8AEBozXjKsllX1D3qMODbfS4Y
TKcXQGbuEIRYOFOGuSnE
=c3An
-----END PGP SIGNATURE-----

**Comment by Walkman100** [comment]
Stop doing that FFS

**Comment by Walkman100** [comment]
61b512ec7eab467f65a2de11b936dedcb70e6158

**Comment by deavmi** [comment]
Yay man.
