### ISSUE TITLE
Low resolution Taskbar icon

### ISSUE THREAD

**Issue by jackwilsdon** [Walkman100/BasicBrowser#6]
It seems that a higher resolution taskbar icon has not been provided. Currently it looks like this;

![](http://i.imgur.com/SVxTYwx.png)

**Comment by Walkman100** [comment]
Yeah, that's just a random icon I found. Previously I didn't have an icon, so I thought this was better than nothing, but I don't really know what to use.
Current icon is `/Resources/1371846583_internet-web-browser.ico` ![browser icon](https://raw.githubusercontent.com/Walkman100/BasicBrowser/master/Resources/1371846583_internet-web-browser.ico)

**Comment by Walkman100** [comment]
85a47f3450dedb4df1f825f6355287127d783158
![icon](https://raw.githubusercontent.com/Walkman100/BasicBrowser/85a47f3450dedb4df1f825f6355287127d783158/Resources/internet2.ico)
I will publish a release soon.

**Comment by Walkman100** [comment]
As of [release v1.2.2](https://github.com/Walkman100/BasicBrowser/releases/tag/v1.2.2) this should be fixed, @jackwilsdon can you confirm?

**Comment by jackwilsdon** [comment]
I can confirm that release 1.2.2 fixes the icon.

**Comment by Walkman100** [comment]
Awesome
